// api/coupon/coupon.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/coupon/coupon.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Campaign represents a coupon campaign
type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalCoupons  int32                  `protobuf:"varint,3,opt,name=total_coupons,json=totalCoupons,proto3" json:"total_coupons,omitempty"`
	IssuedCoupons int32                  `protobuf:"varint,4,opt,name=issued_coupons,json=issuedCoupons,proto3" json:"issued_coupons,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_api_coupon_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetTotalCoupons() int32 {
	if x != nil {
		return x.TotalCoupons
	}
	return 0
}

func (x *Campaign) GetIssuedCoupons() int32 {
	if x != nil {
		return x.IssuedCoupons
	}
	return 0
}

func (x *Campaign) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Coupon represents an issued coupon
type Coupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coupon) Reset() {
	*x = Coupon{}
	mi := &file_api_coupon_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coupon) ProtoMessage() {}

func (x *Coupon) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coupon.ProtoReflect.Descriptor instead.
func (*Coupon) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *Coupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Coupon) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *Coupon) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

// CreateCampaignRequest is the request for creating a new campaign
type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TotalCoupons  int32                  `protobuf:"varint,2,opt,name=total_coupons,json=totalCoupons,proto3" json:"total_coupons,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_api_coupon_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetTotalCoupons() int32 {
	if x != nil {
		return x.TotalCoupons
	}
	return 0
}

func (x *CreateCampaignRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// CreateCampaignResponse is the response for creating a new campaign
type CreateCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse) Reset() {
	*x = CreateCampaignResponse{}
	mi := &file_api_coupon_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse) ProtoMessage() {}

func (x *CreateCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

// GetCampaignRequest is the request for getting campaign information
type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_api_coupon_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *GetCampaignRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

// GetCampaignResponse is the response for getting campaign information
type GetCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Coupons       []*Coupon              `protobuf:"bytes,2,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_api_coupon_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *GetCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

func (x *GetCampaignResponse) GetCoupons() []*Coupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

// IssueCouponRequest is the request for issuing a coupon
type IssueCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponRequest) Reset() {
	*x = IssueCouponRequest{}
	mi := &file_api_coupon_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponRequest) ProtoMessage() {}

func (x *IssueCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponRequest.ProtoReflect.Descriptor instead.
func (*IssueCouponRequest) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *IssueCouponRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

// IssueCouponResponse is the response for issuing a coupon
type IssueCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Coupon        *Coupon                `protobuf:"bytes,2,opt,name=coupon,proto3" json:"coupon,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponResponse) Reset() {
	*x = IssueCouponResponse{}
	mi := &file_api_coupon_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponResponse) ProtoMessage() {}

func (x *IssueCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_coupon_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponResponse.ProtoReflect.Descriptor instead.
func (*IssueCouponResponse) Descriptor() ([]byte, []int) {
	return file_api_coupon_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *IssueCouponResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IssueCouponResponse) GetCoupon() *Coupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

func (x *IssueCouponResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_coupon_coupon_proto protoreflect.FileDescriptor

const file_api_coupon_coupon_proto_rawDesc = "" +
	"\n" +
	"\x17api/coupon/coupon.proto\x12\tcoupon.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rtotal_coupons\x18\x03 \x01(\x05R\ftotalCoupons\x12%\n" +
	"\x0eissued_coupons\x18\x04 \x01(\x05R\rissuedCoupons\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"v\n" +
	"\x06Coupon\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x127\n" +
	"\tissued_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"\x8b\x01\n" +
	"\x15CreateCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rtotal_coupons\x18\x02 \x01(\x05R\ftotalCoupons\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"I\n" +
	"\x16CreateCampaignResponse\x12/\n" +
	"\bcampaign\x18\x01 \x01(\v2\x13.coupon.v1.CampaignR\bcampaign\"5\n" +
	"\x12GetCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"s\n" +
	"\x13GetCampaignResponse\x12/\n" +
	"\bcampaign\x18\x01 \x01(\v2\x13.coupon.v1.CampaignR\bcampaign\x12+\n" +
	"\acoupons\x18\x02 \x03(\v2\x11.coupon.v1.CouponR\acoupons\"5\n" +
	"\x12IssueCouponRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"p\n" +
	"\x13IssueCouponResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x06coupon\x18\x02 \x01(\v2\x11.coupon.v1.CouponR\x06coupon\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x88\x02\n" +
	"\rCouponService\x12W\n" +
	"\x0eCreateCampaign\x12 .coupon.v1.CreateCampaignRequest\x1a!.coupon.v1.CreateCampaignResponse\"\x00\x12N\n" +
	"\vGetCampaign\x12\x1d.coupon.v1.GetCampaignRequest\x1a\x1e.coupon.v1.GetCampaignResponse\"\x00\x12N\n" +
	"\vIssueCoupon\x12\x1d.coupon.v1.IssueCouponRequest\x1a\x1e.coupon.v1.IssueCouponResponse\"\x00B@Z>github.com/rpranjan11/coupon-issuance-system/api/coupon;couponb\x06proto3"

var (
	file_api_coupon_coupon_proto_rawDescOnce sync.Once
	file_api_coupon_coupon_proto_rawDescData []byte
)

func file_api_coupon_coupon_proto_rawDescGZIP() []byte {
	file_api_coupon_coupon_proto_rawDescOnce.Do(func() {
		file_api_coupon_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_coupon_coupon_proto_rawDesc), len(file_api_coupon_coupon_proto_rawDesc)))
	})
	return file_api_coupon_coupon_proto_rawDescData
}

var file_api_coupon_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_coupon_coupon_proto_goTypes = []any{
	(*Campaign)(nil),               // 0: coupon.v1.Campaign
	(*Coupon)(nil),                 // 1: coupon.v1.Coupon
	(*CreateCampaignRequest)(nil),  // 2: coupon.v1.CreateCampaignRequest
	(*CreateCampaignResponse)(nil), // 3: coupon.v1.CreateCampaignResponse
	(*GetCampaignRequest)(nil),     // 4: coupon.v1.GetCampaignRequest
	(*GetCampaignResponse)(nil),    // 5: coupon.v1.GetCampaignResponse
	(*IssueCouponRequest)(nil),     // 6: coupon.v1.IssueCouponRequest
	(*IssueCouponResponse)(nil),    // 7: coupon.v1.IssueCouponResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_api_coupon_coupon_proto_depIdxs = []int32{
	8,  // 0: coupon.v1.Campaign.start_time:type_name -> google.protobuf.Timestamp
	8,  // 1: coupon.v1.Campaign.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: coupon.v1.Coupon.issued_at:type_name -> google.protobuf.Timestamp
	8,  // 3: coupon.v1.CreateCampaignRequest.start_time:type_name -> google.protobuf.Timestamp
	0,  // 4: coupon.v1.CreateCampaignResponse.campaign:type_name -> coupon.v1.Campaign
	0,  // 5: coupon.v1.GetCampaignResponse.campaign:type_name -> coupon.v1.Campaign
	1,  // 6: coupon.v1.GetCampaignResponse.coupons:type_name -> coupon.v1.Coupon
	1,  // 7: coupon.v1.IssueCouponResponse.coupon:type_name -> coupon.v1.Coupon
	2,  // 8: coupon.v1.CouponService.CreateCampaign:input_type -> coupon.v1.CreateCampaignRequest
	4,  // 9: coupon.v1.CouponService.GetCampaign:input_type -> coupon.v1.GetCampaignRequest
	6,  // 10: coupon.v1.CouponService.IssueCoupon:input_type -> coupon.v1.IssueCouponRequest
	3,  // 11: coupon.v1.CouponService.CreateCampaign:output_type -> coupon.v1.CreateCampaignResponse
	5,  // 12: coupon.v1.CouponService.GetCampaign:output_type -> coupon.v1.GetCampaignResponse
	7,  // 13: coupon.v1.CouponService.IssueCoupon:output_type -> coupon.v1.IssueCouponResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_coupon_coupon_proto_init() }
func file_api_coupon_coupon_proto_init() {
	if File_api_coupon_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_coupon_coupon_proto_rawDesc), len(file_api_coupon_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_coupon_coupon_proto_goTypes,
		DependencyIndexes: file_api_coupon_coupon_proto_depIdxs,
		MessageInfos:      file_api_coupon_coupon_proto_msgTypes,
	}.Build()
	File_api_coupon_coupon_proto = out.File
	file_api_coupon_coupon_proto_goTypes = nil
	file_api_coupon_coupon_proto_depIdxs = nil
}
